### ISSUE TITLE
Scenario rather than step error message is not returning the correct error

### ISSUE THREAD

**Issue by jronald01** [iljabauer/behave-teamcity#1]
Hi,

I've been using behave-teamcity and have encountered an issue when an error occurs in a step that is _not the last step_ of the behave feature file.

To correct it, I've locally changed line **53** from:
- error_details = self.current_step.error_message
  to:
- error_details = **step_result**.error_message

**Example Feature fie:**
1. Given I create an API request
2. When I get the request
3. Then the http status should be 200

If my error occurred on lines 1 or 2 of my feature file (in the example above), then the step failed teamcity message would not contain the **details** section, but it did contain the **message** section, which tells you which step has failed but not _why_ it has failed.

When I changed line 53, as I mentioned above, I did then see the relevant exception I had generated when these occurred in lines 1 or 2 in my feature file.

Thanks,
Jim

**Comment by iljabauer** [comment]
Thank for the report. I will correct this or do you want to submit a pull request?

**Comment by jronald01** [comment]
Hi,

It might be easier for you to change it if that's okay?  I've not submitted a github pull request before!

Actually, scratch that!  Pull request created! (https://github.com/iljabauer/behave-teamcity/pull/2)

Thanks,
Jim

**Comment by iljabauer** [comment]
Thanks. I will give it a try on my projects. If everything is fine, I will release a new version to pypi
